package com.kojin15.workbenchplus

import com.kojin15.workbenchplus.WorkbenchPlus.DEPENDENCIES
import com.kojin15.workbenchplus.WorkbenchPlus.KOTLIN_ADAPTER
import com.kojin15.workbenchplus.WorkbenchPlus.MOD_ID
import com.kojin15.workbenchplus.WorkbenchPlus.MOD_NAME
import com.kojin15.workbenchplus.WorkbenchPlus.MOD_VERSION
import com.kojin15.workbenchplus.block.BlockWorkbenchPlus
import net.minecraftforge.fml.common.*
import net.minecraftforge.fml.common.event.FMLConstructionEvent
import net.minecraftforge.fml.common.event.FMLInitializationEvent
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent
import net.toliner.korgelin.Korgelin

/**
 * @author kojin15.
 */
@Mod(modid = MOD_ID, name = MOD_NAME, version = MOD_VERSION, acceptedMinecraftVersions = "[1.12]",
        modLanguage = "kotlin", modLanguageAdapter = KOTLIN_ADAPTER, dependencies = DEPENDENCIES, useMetadata = true)
object WorkbenchPlus {
    const val MOD_ID = "workbenchplus"
    const val MOD_NAME = "Workbench Plus"
    const val MOD_VERSION = "1.1.0"

    const val KOTLIN_ADAPTER = "net.toliner.korgelin.KotlinAdapter"
    const val DEPENDENCIES = "required-after:${Korgelin.MOD_ID};"

    @Mod.Metadata
    private lateinit var METADATA: ModMetadata

    @SidedProxy(clientSide = "com.kojin15.workbenchplus.proxy.ClientProxy",
            serverSide = "com.kojin15.workbenchplus.proxy.ServerProxy")
    lateinit var PROXY: CommonProxy

    @Mod.EventHandler
    fun construct(event: FMLConstructionEvent) {
        METADATA.modId = MOD_ID
        METADATA.name = MOD_NAME
        METADATA.description = "A workbench that automatically refills when item runs out"

        METADATA.url = "https://minecraft.curseforge.com/projects/workbench-plus"

        METADATA.version = MOD_VERSION
        METADATA.authorList.add("kojin15")

        METADATA.autogenerated = false
    }

    @Mod.EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        PROXY.preInit()
    }

    @Mod.EventHandler
    fun init(event: FMLInitializationEvent) {
        PROXY.init()
    }

    @Mod.EventHandler
    fun postInit(event: FMLPostInitializationEvent) {
        PROXY.postInit()
    }

    object Blocks {
        @JvmField val workbenchplus = BlockWorkbenchPlus().setRegistryName(MOD_ID, "workbenchplus")
    }
}